bigquery:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: oauth
      project: my_project
      dataset: indicators_dev     # ← fixed dev schema
      threads: 4

    prod:
      type: bigquery
      method: oauth
      project: my_project
      dataset: indicators_prod   # ← fixed prod schema
      threads: 4
